 CREATE TABLE `student_1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(23) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `PASSWORD` VARCHAR(32) DEFAULT NULL,
  `sex` VARCHAR(8) DEFAULT NULL,
  `stuid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `attendence` TINYINT(1) DEFAULT NULL,
  `classid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=97901 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci